version: "3"
services:
  teejay:
    image: teejay
    ports:
      - "8080:8080"
    networks:
      - teejay-mysql
    depends_on:
      - mysqldb
 
  mysqldb:
    image: mysql:8
    networks:
      - teejay-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=teejay  

networks:
  teejay-mysql: 